services:
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - letsencrypt:/letsencrypt
    networks:
      - traefik-public

volumes:
  letsencrypt:

networks:
  traefik-public:
    external: true
